ERROR 2025-03-23 17:09:31,468 log 1150938 132631083611840 Internal Server Error: /classroom/submit-exam/
ERROR 2025-03-23 17:09:31,471 basehttp 1150938 132631083611840 "POST /classroom/submit-exam/ HTTP/1.1" 500 114
ERROR 2025-03-23 17:24:34,908 log 1214210 123424882312896 Internal Server Error: /results/detail/5/
Traceback (most recent call last):
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/results/views.py", line 272, in view_result_detail
    student_answer = responses.get(str(question.id), None)
                     ^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
ERROR 2025-03-23 17:24:34,910 basehttp 1214210 123424882312896 "GET /results/detail/5/ HTTP/1.1" 500 78888
ERROR 2025-03-23 17:48:13,527 views 6741 137322603456192 Error fetching exam details: unsupported type for timedelta minutes component: datetime.timedelta
Traceback (most recent call last):
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/monitoring/views.py", line 449, in api_exam_details
    end_time = start_datetime + datetime.timedelta(minutes=exam.exam_duration)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported type for timedelta minutes component: datetime.timedelta
ERROR 2025-03-23 17:48:13,542 log 6741 137322603456192 Internal Server Error: /monitoring/api/exam/6/details/
ERROR 2025-03-23 17:48:13,563 basehttp 6741 137322603456192 "GET /monitoring/api/exam/6/details/ HTTP/1.1" 500 41
ERROR 2025-03-23 17:48:14,592 views 6741 137322224010944 Error fetching exam details: unsupported type for timedelta minutes component: datetime.timedelta
Traceback (most recent call last):
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/monitoring/views.py", line 449, in api_exam_details
    end_time = start_datetime + datetime.timedelta(minutes=exam.exam_duration)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported type for timedelta minutes component: datetime.timedelta
ERROR 2025-03-23 17:48:14,593 log 6741 137322224010944 Internal Server Error: /monitoring/api/exam/6/details/
ERROR 2025-03-23 17:48:14,606 basehttp 6741 137322224010944 "GET /monitoring/api/exam/6/details/ HTTP/1.1" 500 41
ERROR 2025-03-23 17:48:24,252 frame_processor 6741 137322022553280 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-23 17:48:24,259 frame_processor 6741 137322030945984 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-23 17:48:24,377 frame_processor 6741 137324744951488 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-23 17:48:24,416 frame_processor 6741 137324667074240 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-23 17:48:36,772 frame_processor 6741 137321744967360 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-23 17:48:46,583 frame_processor 6741 137321753360064 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-23 17:53:25,922 frame_processor 26740 131891182171840 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-23 17:53:25,923 frame_processor 26740 131893038413504 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-23 17:53:25,942 frame_processor 26740 131893055198912 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-23 17:53:25,962 frame_processor 26740 131893046806208 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[3,3,512,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-23 17:53:26,051 frame_processor 26740 131889151063744 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-23 17:53:26,065 frame_processor 26740 131889159456448 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[3,3,256,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:22:07,994 frame_processor 139331 127329601078976 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-25 05:22:08,172 frame_processor 139331 127329592686272 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-25 05:22:08,216 frame_processor 139331 127327358940864 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[3,3,256,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:22:56,065 frame_processor 142779 129675415254720 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-25 05:23:06,231 frame_processor 142779 129677092206272 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-25 05:23:06,302 frame_processor 142779 129677083813568 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[3,3,512,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:23:06,398 frame_processor 142779 129673082156736 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-25 05:23:06,407 frame_processor 142779 129673090549440 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[3,3,128,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:23:06,417 frame_processor 142779 129677100598976 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[3,3,128,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:23:38,320 frame_processor 142779 129675415254720 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:23:40,405 frame_processor 142779 129673082156736 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:23:48,148 frame_processor 142779 129673090549440 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-25 05:23:48,163 frame_processor 142779 129677083813568 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-25 05:23:48,429 frame_processor 142779 129677100598976 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-25 05:23:48,441 frame_processor 142779 129677092206272 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[3,3,512,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:24:21,964 frame_processor 142779 129673090549440 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:24:31,029 frame_processor 142779 129673082156736 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-25 05:24:31,178 frame_processor 142779 129675415254720 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:24:33,020 frame_processor 142779 129677083813568 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:24:33,149 frame_processor 142779 129677092206272 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:24:33,181 frame_processor 142779 129677100598976 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:25:21,813 frame_processor 142779 129673090549440 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:25:21,852 frame_processor 142779 129675415254720 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:25:22,170 frame_processor 142779 129673082156736 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:25:22,171 frame_processor 142779 129677083813568 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:25:32,291 frame_processor 142779 129677100598976 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:25:32,814 frame_processor 142779 129677092206272 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:25:54,900 frame_processor 142779 129675415254720 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:25:55,310 frame_processor 142779 129677083813568 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:25:55,353 frame_processor 142779 129673090549440 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:25:55,382 frame_processor 142779 129673082156736 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:26:03,399 frame_processor 142779 129677100598976 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:26:04,191 frame_processor 142779 129677092206272 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:26:36,323 frame_processor 142779 129673082156736 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[3,3,128,128] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:26:48,024 frame_processor 142779 129675415254720 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:26:48,057 frame_processor 142779 129677100598976 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:26:48,104 frame_processor 142779 129673090549440 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:26:48,121 frame_processor 142779 129677083813568 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:26:58,100 frame_processor 142779 129677092206272 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:27:09,896 frame_processor 142779 129673082156736 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:27:20,367 frame_processor 142779 129677100598976 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:27:20,392 frame_processor 142779 129675415254720 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:27:20,876 frame_processor 142779 129673090549440 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:27:20,895 frame_processor 142779 129677083813568 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:27:25,373 log 142779 129672469800640 Internal Server Error: /classroom/submit-exam/
ERROR 2025-03-25 05:27:25,374 basehttp 142779 129672469800640 "POST /classroom/submit-exam/ HTTP/1.1" 500 114
ERROR 2025-03-25 05:27:27,410 log 142779 129672662734528 Internal Server Error: /classroom/submit-exam/
ERROR 2025-03-25 05:27:27,411 basehttp 142779 129672662734528 "POST /classroom/submit-exam/ HTTP/1.1" 500 114
ERROR 2025-03-25 05:27:29,092 frame_processor 142779 129677092206272 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:27:43,943 frame_processor 142779 129672679519936 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:27:43,969 frame_processor 142779 129672864061120 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:27:43,986 frame_processor 142779 129672872453824 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:27:44,001 frame_processor 142779 129673082156736 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:27:45,561 frame_processor 142779 129672461407936 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 05:27:45,605 frame_processor 142779 129672478193344 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 10:04:02,053 log 98150 138076902815424 Internal Server Error: /classroom/submit-exam/
ERROR 2025-03-25 10:04:02,055 log 98150 138076756113088 Internal Server Error: /classroom/submit-exam/
ERROR 2025-03-25 10:04:02,055 basehttp 98150 138076902815424 "POST /classroom/submit-exam/ HTTP/1.1" 500 114
ERROR 2025-03-25 10:04:02,055 basehttp 98150 138076756113088 "POST /classroom/submit-exam/ HTTP/1.1" 500 114
ERROR 2025-03-25 10:04:04,089 log 98150 138076756113088 Internal Server Error: /classroom/submit-exam/
ERROR 2025-03-25 10:04:04,089 basehttp 98150 138076756113088 "POST /classroom/submit-exam/ HTTP/1.1" 500 114
ERROR 2025-03-25 10:04:04,104 log 98150 138076902815424 Internal Server Error: /classroom/submit-exam/
ERROR 2025-03-25 10:04:04,104 basehttp 98150 138076902815424 "POST /classroom/submit-exam/ HTTP/1.1" 500 114
ERROR 2025-03-25 10:04:08,125 log 98150 138076902815424 Internal Server Error: /classroom/submit-exam/
ERROR 2025-03-25 10:04:08,125 basehttp 98150 138076902815424 "POST /classroom/submit-exam/ HTTP/1.1" 500 114
ERROR 2025-03-25 10:04:08,138 log 98150 138076756113088 Internal Server Error: /classroom/submit-exam/
ERROR 2025-03-25 10:04:08,138 basehttp 98150 138076756113088 "POST /classroom/submit-exam/ HTTP/1.1" 500 114
ERROR 2025-03-25 11:52:50,335 frame_processor 70394 125706317067968 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-25 11:52:50,362 frame_processor 70394 125704316753600 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-25 11:52:50,390 frame_processor 70394 125705618712256 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 11:53:13,551 frame_processor 70394 125704325146304 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 11:53:13,847 frame_processor 70394 125704308360896 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-25 11:53:23,169 frame_processor 70394 125704333539008 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-25 11:53:33,203 frame_processor 70394 125706317067968 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-26 06:03:57,497 log 175987 131546988144320 Internal Server Error: /classroom/submit-exam/
ERROR 2025-03-26 06:03:57,505 basehttp 175987 131546988144320 "POST /classroom/submit-exam/ HTTP/1.1" 500 114
ERROR 2025-03-26 06:03:59,536 log 175987 131547547088576 Internal Server Error: /classroom/submit-exam/
ERROR 2025-03-26 06:19:31,873 log 232810 125450655274688 Internal Server Error: /results/review/7/
Traceback (most recent call last):
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/results/views.py", line 132, in review_flagged_exam
    session = ExamSession.objects.get(student=result.student, exam=result.exam)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/db/models/query.py", line 652, in get
    raise self.model.MultipleObjectsReturned(
monitoring.models.ExamSession.MultipleObjectsReturned: get() returned more than one ExamSession -- it returned 2!
ERROR 2025-03-26 06:19:31,879 basehttp 232810 125450655274688 "GET /results/review/7/ HTTP/1.1" 500 88166
ERROR 2025-03-26 06:19:50,246 log 232810 125450655274688 Internal Server Error: /results/review/7/
Traceback (most recent call last):
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/results/views.py", line 132, in review_flagged_exam
    session = ExamSession.objects.get(student=result.student, exam=result.exam)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/db/models/query.py", line 652, in get
    raise self.model.MultipleObjectsReturned(
monitoring.models.ExamSession.MultipleObjectsReturned: get() returned more than one ExamSession -- it returned 2!
ERROR 2025-03-26 06:19:50,248 basehttp 232810 125450655274688 "GET /results/review/7/ HTTP/1.1" 500 87901
ERROR 2025-03-26 06:20:42,381 log 232810 125450655274688 Internal Server Error: /results/review/7/
Traceback (most recent call last):
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/results/views.py", line 132, in review_flagged_exam
    session = ExamSession.objects.get(student=result.student, exam=result.exam)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/db/models/query.py", line 652, in get
    raise self.model.MultipleObjectsReturned(
monitoring.models.ExamSession.MultipleObjectsReturned: get() returned more than one ExamSession -- it returned 2!
ERROR 2025-03-26 06:20:42,382 basehttp 232810 125450655274688 "GET /results/review/7/ HTTP/1.1" 500 87901
ERROR 2025-03-26 06:22:20,690 log 232810 125451248858816 Internal Server Error: /results/review/7/
Traceback (most recent call last):
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/results/views.py", line 132, in review_flagged_exam
    session = ExamSession.objects.get(student=result.student, exam=result.exam)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/db/models/query.py", line 652, in get
    raise self.model.MultipleObjectsReturned(
monitoring.models.ExamSession.MultipleObjectsReturned: get() returned more than one ExamSession -- it returned 2!
ERROR 2025-03-26 06:22:20,693 basehttp 232810 125451248858816 "GET /results/review/7/ HTTP/1.1" 500 87945
ERROR 2025-03-26 06:40:31,619 frame_processor 350120 131128528942784 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[3,3,512,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 06:40:31,628 frame_processor 350120 131128537335488 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-26 06:40:42,720 frame_processor 350120 131119677216448 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-26 06:40:42,739 frame_processor 350120 131119915726528 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 06:40:42,776 frame_processor 350120 131120276424384 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 06:40:42,810 frame_processor 350120 131119870150336 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 06:40:42,834 frame_processor 350120 131119861757632 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 06:40:42,850 frame_processor 350120 131119668823744 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 06:41:34,570 frame_processor 350120 131119677216448 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-26 06:41:34,599 frame_processor 350120 131119196403392 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-26 06:41:34,621 frame_processor 350120 131119861757632 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[3,3,512,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 06:41:34,627 frame_processor 350120 131119915726528 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[3,3,256,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 06:41:34,641 frame_processor 350120 131119668823744 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-26 06:41:34,668 frame_processor 350120 131119870150336 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[3,3,256,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 06:43:58,723 frame_processor 363337 133317051541184 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 06:43:58,730 frame_processor 363337 133317142005440 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 06:46:42,597 frame_processor 373474 133991782557376 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-26 09:51:15,743 frame_processor 127926 130967356589760 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-26 09:51:15,776 frame_processor 127926 130967348197056 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:51:37,608 frame_processor 127926 130964925822656 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-26 09:51:37,672 frame_processor 127926 130964290270912 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:51:47,706 frame_processor 127926 130964909037248 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-26 09:51:47,778 frame_processor 127926 130964917429952 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:52:08,546 frame_processor 127926 130964244694720 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-26 09:52:08,563 frame_processor 127926 130964236302016 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:52:19,829 frame_processor 127926 130965112350400 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:52:28,908 frame_processor 127926 130964290270912 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-26 09:52:30,105 frame_processor 127926 130964925822656 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:52:38,773 frame_processor 127926 130964917429952 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-26 09:52:59,450 frame_processor 127926 130967348197056 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:52:59,463 frame_processor 127926 130964244694720 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:53:10,181 frame_processor 127926 130965112350400 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-26 09:53:29,948 frame_processor 127926 130964290270912 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:53:29,998 frame_processor 127926 130964917429952 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:53:30,064 frame_processor 127926 130964925822656 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:53:40,567 frame_processor 127926 130964244694720 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:53:41,183 frame_processor 127926 130967348197056 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:53:51,757 frame_processor 127926 130965112350400 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:54:02,242 frame_processor 127926 130964290270912 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:54:02,276 frame_processor 127926 130964925822656 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:54:02,448 frame_processor 127926 130964917429952 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:54:11,398 frame_processor 127926 130964244694720 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:54:12,930 frame_processor 127926 130967348197056 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:54:23,749 frame_processor 127926 130965112350400 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:54:33,870 frame_processor 127926 130964290270912 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:54:33,938 frame_processor 127926 130964925822656 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:54:34,116 frame_processor 127926 130964917429952 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:54:42,153 frame_processor 127926 130964244694720 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:54:44,358 frame_processor 127926 130967348197056 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:54:55,467 frame_processor 127926 130965112350400 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:55:15,104 frame_processor 127926 130964290270912 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-26 09:55:15,120 frame_processor 127926 130964917429952 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-26 09:55:15,146 frame_processor 127926 130964925822656 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-26 09:55:15,168 frame_processor 127926 130964244694720 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[3,3,128,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:55:15,205 frame_processor 127926 130967348197056 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-26 09:55:37,403 frame_processor 127926 130965112350400 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:55:47,696 frame_processor 127926 130964290270912 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:55:48,357 frame_processor 127926 130964925822656 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:55:48,630 frame_processor 127926 130964244694720 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:55:48,655 frame_processor 127926 130964917429952 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:55:48,663 frame_processor 127926 130967348197056 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:56:08,807 frame_processor 127926 130965112350400 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:56:18,519 frame_processor 127926 130964290270912 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:56:19,402 frame_processor 127926 130964925822656 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:56:20,471 frame_processor 127926 130964917429952 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:56:20,555 frame_processor 127926 130967348197056 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:56:20,570 frame_processor 127926 130964244694720 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:56:39,972 frame_processor 127926 130965112350400 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:56:51,983 frame_processor 127926 130964290270912 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-26 09:56:52,034 frame_processor 127926 130964917429952 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-26 09:56:52,075 frame_processor 127926 130964925822656 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-26 09:56:52,101 frame_processor 127926 130967348197056 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[3,3,128,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:56:52,123 frame_processor 127926 130964244694720 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-26 09:57:23,191 frame_processor 127926 130965112350400 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:57:23,915 frame_processor 127926 130964290270912 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:57:35,420 frame_processor 127926 130967348197056 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:57:35,435 frame_processor 127926 130964917429952 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:57:35,451 frame_processor 127926 130964244694720 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:57:35,562 frame_processor 127926 130964925822656 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:57:38,796 frame_processor 127926 130964236302016 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:57:40,878 frame_processor 127926 130967356589760 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:57:40,899 frame_processor 127926 130966787974848 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:57:42,890 frame_processor 127926 130964934215360 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:57:45,487 frame_processor 127926 130966779582144 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-26 09:57:46,318 frame_processor 127926 130966771189440 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:58:11,702 frame_processor 127926 130964236302016 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:58:22,017 frame_processor 127926 130967356589760 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-26 09:58:22,035 frame_processor 127926 130966787974848 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[3,3,512,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:58:22,843 frame_processor 127926 130964934215360 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-26 09:58:22,869 frame_processor 127926 130966771189440 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[3,3,256,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:58:22,884 frame_processor 127926 130966779582144 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[3,3,256,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 09:58:53,678 frame_processor 127926 130964236302016 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 10:06:28,784 frame_processor 185683 135599329920704 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 10:06:28,786 frame_processor 185683 135599321528000 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-26 10:06:49,706 frame_processor 185683 135597033240256 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 10:06:49,718 frame_processor 185683 135597041632960 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 10:07:02,751 frame_processor 185683 135596168210112 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-26 10:07:02,916 frame_processor 185683 135596159817408 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 10:07:12,769 frame_processor 185683 135599321528000 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-26 10:07:13,812 frame_processor 185683 135599329920704 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 10:07:20,852 frame_processor 185683 135597033240256 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 10:07:24,101 frame_processor 185683 135597041632960 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 10:08:03,265 frame_processor 185683 135596168210112 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-26 10:08:03,372 frame_processor 185683 135596159817408 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 10:08:03,384 frame_processor 185683 135597033240256 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 10:08:03,441 frame_processor 185683 135599321528000 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 10:08:13,858 frame_processor 185683 135597041632960 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-26 10:08:13,931 frame_processor 185683 135599329920704 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[3,3,512,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-26 10:17:34,145 frame_processor 227328 125265137387200 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-26 21:38:32,240 log 588897 140571366926016 Internal Server Error: /classroom/submit-exam/
ERROR 2025-03-26 21:38:32,241 basehttp 588897 140571366926016 "POST /classroom/submit-exam/ HTTP/1.1" 500 114
ERROR 2025-03-26 21:38:34,263 log 588897 140568013293248 Internal Server Error: /classroom/submit-exam/
ERROR 2025-03-26 21:38:34,264 basehttp 588897 140568013293248 "POST /classroom/submit-exam/ HTTP/1.1" 500 114
ERROR 2025-03-26 22:56:09,929 log 916636 128267260806848 Internal Server Error: /results/review/8/
Traceback (most recent call last):
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/results/views.py", line 155, in review_flagged_exam
    return render(request, 'results/review_flagged_exam.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 1537, in do_with
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'with' received an invalid token: '=='
ERROR 2025-03-26 22:56:09,933 basehttp 916636 128267260806848 "GET /results/review/8/ HTTP/1.1" 500 365090
ERROR 2025-03-26 22:58:57,401 log 925972 139056443049664 Internal Server Error: /results/review/8/
Traceback (most recent call last):
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/results/views.py", line 155, in review_flagged_exam
    return render(request, 'results/review_flagged_exam.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 1537, in do_with
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'with' received an invalid token: '=='
ERROR 2025-03-26 22:58:57,404 basehttp 925972 139056443049664 "GET /results/review/8/ HTTP/1.1" 500 365090
ERROR 2025-03-26 22:58:59,834 log 925972 139056443049664 Internal Server Error: /results/review/8/
Traceback (most recent call last):
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/results/views.py", line 155, in review_flagged_exam
    return render(request, 'results/review_flagged_exam.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 1537, in do_with
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'with' received an invalid token: '=='
ERROR 2025-03-26 22:58:59,836 basehttp 925972 139056443049664 "GET /results/review/8/ HTTP/1.1" 500 365090
ERROR 2025-03-27 06:02:13,697 log 264316 140659843675840 Internal Server Error: /classroom/submit-exam/
ERROR 2025-03-27 06:02:13,698 basehttp 264316 140659843675840 "POST /classroom/submit-exam/ HTTP/1.1" 500 114
ERROR 2025-03-27 06:02:15,744 log 264316 140656479561408 Internal Server Error: /classroom/submit-exam/
ERROR 2025-03-27 06:02:15,745 basehttp 264316 140656479561408 "POST /classroom/submit-exam/ HTTP/1.1" 500 114
ERROR 2025-03-27 06:03:27,872 views 264316 140659805910720 Error fetching exam details: 'Exam' object has no attribute 'exam_duration'
Traceback (most recent call last):
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/monitoring/views.py", line 452, in api_exam_details
    if isinstance(exam.exam_duration, datetime.timedelta):
                  ^^^^^^^^^^^^^^^^^^
AttributeError: 'Exam' object has no attribute 'exam_duration'
ERROR 2025-03-27 06:03:27,875 log 264316 140659805910720 Internal Server Error: /monitoring/api/exam/2/details/
ERROR 2025-03-27 06:03:27,876 basehttp 264316 140659805910720 "GET /monitoring/api/exam/2/details/ HTTP/1.1" 500 41
ERROR 2025-03-27 06:16:36,057 views 264316 140659835283136 Error fetching exam details: 'Exam' object has no attribute 'exam_duration'
Traceback (most recent call last):
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/monitoring/views.py", line 452, in api_exam_details
    if isinstance(exam.exam_duration, datetime.timedelta):
                  ^^^^^^^^^^^^^^^^^^
AttributeError: 'Exam' object has no attribute 'exam_duration'
ERROR 2025-03-27 06:16:36,059 log 264316 140659835283136 Internal Server Error: /monitoring/api/exam/3/details/
ERROR 2025-03-27 06:16:36,059 basehttp 264316 140659835283136 "GET /monitoring/api/exam/3/details/ HTTP/1.1" 500 41
ERROR 2025-03-27 06:20:14,068 views 264316 140659852068544 Error fetching exam details: 'Exam' object has no attribute 'exam_duration'
Traceback (most recent call last):
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/monitoring/views.py", line 452, in api_exam_details
    if isinstance(exam.exam_duration, datetime.timedelta):
                  ^^^^^^^^^^^^^^^^^^
AttributeError: 'Exam' object has no attribute 'exam_duration'
ERROR 2025-03-27 06:20:14,070 log 264316 140659852068544 Internal Server Error: /monitoring/api/exam/3/details/
ERROR 2025-03-27 06:20:14,071 basehttp 264316 140659852068544 "GET /monitoring/api/exam/3/details/ HTTP/1.1" 500 41
ERROR 2025-03-27 11:43:08,423 views 6244 123638909249216 Error fetching exam details: 'Exam' object has no attribute 'exam_duration'
Traceback (most recent call last):
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/monitoring/views.py", line 452, in api_exam_details
    if isinstance(exam.exam_duration, datetime.timedelta):
                  ^^^^^^^^^^^^^^^^^^
AttributeError: 'Exam' object has no attribute 'exam_duration'
ERROR 2025-03-27 11:43:08,426 log 6244 123638909249216 Internal Server Error: /monitoring/api/exam/3/details/
ERROR 2025-03-27 11:43:08,427 basehttp 6244 123638909249216 "GET /monitoring/api/exam/3/details/ HTTP/1.1" 500 41
ERROR 2025-03-27 17:48:06,156 views 14279 138265944667840 Error fetching exam details: 'Exam' object has no attribute 'exam_duration'
Traceback (most recent call last):
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/monitoring/views.py", line 452, in api_exam_details
    if isinstance(exam.exam_duration, datetime.timedelta):
                  ^^^^^^^^^^^^^^^^^^
AttributeError: 'Exam' object has no attribute 'exam_duration'
ERROR 2025-03-27 17:48:06,161 log 14279 138265944667840 Internal Server Error: /monitoring/api/exam/3/details/
ERROR 2025-03-27 17:48:06,170 basehttp 14279 138265944667840 "GET /monitoring/api/exam/3/details/ HTTP/1.1" 500 41
ERROR 2025-03-27 17:51:39,095 views 14279 138265944667840 Error fetching exam details: 'Exam' object has no attribute 'exam_duration'
Traceback (most recent call last):
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/monitoring/views.py", line 452, in api_exam_details
    if isinstance(exam.exam_duration, datetime.timedelta):
                  ^^^^^^^^^^^^^^^^^^
AttributeError: 'Exam' object has no attribute 'exam_duration'
ERROR 2025-03-27 17:51:39,105 log 14279 138265944667840 Internal Server Error: /monitoring/api/exam/1/details/
ERROR 2025-03-27 17:51:39,105 basehttp 14279 138265944667840 "GET /monitoring/api/exam/1/details/ HTTP/1.1" 500 41
ERROR 2025-03-27 18:00:10,158 views 14279 138265868891840 Error fetching exam details: 'Exam' object has no attribute 'exam_duration'
Traceback (most recent call last):
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/monitoring/views.py", line 452, in api_exam_details
    if isinstance(exam.exam_duration, datetime.timedelta):
                  ^^^^^^^^^^^^^^^^^^
AttributeError: 'Exam' object has no attribute 'exam_duration'
ERROR 2025-03-27 18:00:10,160 log 14279 138265868891840 Internal Server Error: /monitoring/api/exam/3/details/
ERROR 2025-03-27 18:00:10,160 basehttp 14279 138265868891840 "GET /monitoring/api/exam/3/details/ HTTP/1.1" 500 41
ERROR 2025-03-27 18:01:01,121 views 14279 138265944667840 Error fetching exam details: 'Exam' object has no attribute 'exam_duration'
Traceback (most recent call last):
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/monitoring/views.py", line 452, in api_exam_details
    if isinstance(exam.exam_duration, datetime.timedelta):
                  ^^^^^^^^^^^^^^^^^^
AttributeError: 'Exam' object has no attribute 'exam_duration'
ERROR 2025-03-27 18:01:01,123 log 14279 138265944667840 Internal Server Error: /monitoring/api/exam/3/details/
ERROR 2025-03-27 18:01:01,124 basehttp 14279 138265944667840 "GET /monitoring/api/exam/3/details/ HTTP/1.1" 500 41
ERROR 2025-03-27 18:14:19,055 frame_processor 116078 133875486705344 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-27 18:14:19,056 frame_processor 116078 133875405682368 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-27 18:17:02,798 views 116078 133875365836480 Error fetching exam details: 'Exam' object has no attribute 'exam_duration'
Traceback (most recent call last):
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/monitoring/views.py", line 452, in api_exam_details
    if isinstance(exam.exam_duration, datetime.timedelta):
                  ^^^^^^^^^^^^^^^^^^
AttributeError: 'Exam' object has no attribute 'exam_duration'
ERROR 2025-03-27 18:17:02,800 log 116078 133875365836480 Internal Server Error: /monitoring/api/exam/3/details/
ERROR 2025-03-27 18:17:02,801 basehttp 116078 133875365836480 "GET /monitoring/api/exam/3/details/ HTTP/1.1" 500 41
ERROR 2025-03-27 18:23:04,933 views 150011 132153283159744 Error fetching exam details: 'Exam' object has no attribute 'exam_duration'
Traceback (most recent call last):
  File "/home/abhinusekharlal/Desktop/ai_exam_portal/AI_EXAM_PORTAL/monitoring/views.py", line 454, in api_exam_details
    if isinstance(exam.exam_duration, datetime.timedelta):
                  ^^^^^^^^^^^^^^^^^^
AttributeError: 'Exam' object has no attribute 'exam_duration'
ERROR 2025-03-27 18:23:04,936 log 150011 132153283159744 Internal Server Error: /monitoring/api/exam/3/details/
ERROR 2025-03-27 18:23:04,936 basehttp 150011 132153283159744 "GET /monitoring/api/exam/3/details/ HTTP/1.1" 500 41
ERROR 2025-03-27 18:23:05,935 frame_processor 150011 132157326763712 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 18:23:05,967 frame_processor 150011 132154543544000 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 18:23:09,438 frame_processor 150011 132157335156416 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-27 18:36:50,962 frame_processor 201636 138284963743424 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-27 18:36:50,963 frame_processor 201636 138284942763712 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-27 18:36:51,166 frame_processor 201636 138281049818816 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-27 18:36:51,175 frame_processor 201636 138281058211520 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[3,3,512,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 18:37:26,893 frame_processor 201636 138280859330240 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 18:37:31,349 frame_processor 201636 138280850937536 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-27 18:37:31,350 frame_processor 201636 138284942763712 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-27 18:37:31,475 frame_processor 201636 138280867722944 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 18:54:13,704 frame_processor 266268 131148682639040 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-27 18:54:13,718 frame_processor 266268 131147958838976 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 18:54:13,819 frame_processor 266268 131145095939776 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 18:54:14,038 frame_processor 266268 131144712451776 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 18:54:14,052 frame_processor 266268 131148674246336 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 18:54:14,070 frame_processor 266268 131145112725184 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 18:59:05,579 frame_processor 286784 127303990294208 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-27 18:59:05,595 frame_processor 286784 127303981901504 DeepFace verification error: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run _EagerConst: Dst tensor is not initialized.
ERROR 2025-03-27 18:59:36,770 frame_processor 286784 127305562883776 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 18:59:37,203 frame_processor 286784 127306133944000 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-27 18:59:37,326 frame_processor 286784 127306142336704 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 18:59:38,554 frame_processor 286784 127303981901504 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 18:59:46,399 frame_processor 286784 127301924681408 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-27 18:59:46,532 frame_processor 286784 127303990294208 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 19:00:09,627 frame_processor 286784 127305562883776 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 19:00:17,516 frame_processor 286784 127306133944000 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-27 19:00:17,636 frame_processor 286784 127306142336704 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 19:00:17,983 frame_processor 286784 127303981901504 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 19:00:18,355 frame_processor 286784 127301924681408 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 19:00:19,023 frame_processor 286784 127303990294208 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 19:00:58,489 frame_processor 286784 127305562883776 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 19:00:58,601 frame_processor 286784 127301924681408 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-27 19:00:58,622 frame_processor 286784 127303981901504 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[3,3,512,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 19:00:58,652 frame_processor 286784 127306133944000 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[3,3,512,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 19:00:58,675 frame_processor 286784 127306142336704 DeepFace verification error: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
ERROR 2025-03-27 19:01:09,135 frame_processor 286784 127303990294208 DeepFace verification error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2] name: 
ERROR 2025-03-27 19:01:30,398 frame_processor 286784 127305562883776 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 19:01:31,274 frame_processor 286784 127301924681408 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 19:01:31,902 frame_processor 286784 127306133944000 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 19:01:31,941 frame_processor 286784 127303981901504 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 19:01:40,568 frame_processor 286784 127306142336704 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 19:01:50,508 frame_processor 286784 127303990294208 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 19:02:01,580 frame_processor 286784 127305562883776 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
ERROR 2025-03-27 19:02:03,012 frame_processor 286784 127301924681408 DeepFace verification error: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[7,7,512,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StatelessRandomUniformV2] name: 
